test: false

# spring
#spring:
#  main:
#    web-environment: false

server:
  port: 8081

# cinema-bot
bot:
  schedule:
    fixedDelay: 60000
  telegram:
    apiDomain: https://api.telegram.org
    token:
    chatId: 451573335
    channel: cinema1p1
    username: ksgTestBot
    api:
      sendMessage: https://api.telegram.org/bot%s/sendMessage
  cinema:
    lotte:
      api: http://www.lottecinema.co.kr/LCWS/CinemaMall/CinemaMallData.aspx
    cgv:
      api: http://www.cgv.co.kr/culture-event/event
